### ISSUE TITLE
docker-compose command not found

### ISSUE THREAD

**Issue by mgkahn** [Andrew0Hill/NURS6293_environment#1]
MacOS.
Docker version 4.33.0
launchDesktop.sh: Line 4: docker-compose up -d

(base) AndrewOHill/NURS6293_environment[mgk L|✚1] % docker-compose
zsh: command not found: docker-compose

docker compose works.

**Comment by Andrew0Hill** [comment]
Interesting, this must have just recently changed (I'm on 4.31.0). I'll update the scripts to use `dockercompose` instead.

**Comment by mgkahn** [comment]
It is docker-space-compose. There is a space between docker and compose.
The space got suppressed by Markdown.

**Comment by mgkahn** [comment]
Fixed.
