### ISSUE TITLE
Change default GUI login from abc to student

### ISSUE THREAD

**Issue by mgkahn** [Andrew0Hill/NURS6293_environment#12]
I think this one is already done. If so, close the issue.

**Comment by Andrew0Hill** [comment]
Tried the `CUSTOM_USER` environment variable, but this seems to be unrelated to the abc user. 

Per [this issue](https://github.com/linuxserver/docker-webtop/issues/163), changing the abc username is unsupported. 

For a workaround, we can change the PS1 string used by bash to remove a reference to `abc` and the container hash.
