### ISSUE TITLE
Postgres initdb error: "Current user cannot be dropped"

### ISSUE THREAD

**Issue by mgkahn** [Andrew0Hill/NURS6293_environment#19]
Error with executing nurs6293_createdb.sql.gz in initdb context. See error log screenshot.
Error not seen in psql testing environment.

![initdb_error](https://github.com/user-attachments/assets/6ac9acc8-f059-43a7-a0f7-445eae23e48e)

**Comment by mgkahn** [comment]
Fix implemented in new `initdb_fix` branch.

Issue caused by a difference in Postgres initialization between development and production Docker images. Development image does not call `initdb` before executing scripts in `/docker-entrypoint-initdb.d` Production docker PG image calls `initdb` and then calls scripts in `/docker-entrypoint-initdb.d`. The call to `initdb` creates the postgres superuser. See attached screen shot from dockerhub Postgres overview: https://hub.docker.com/_/postgres 

<img width="1168" alt="image" src="https://github.com/user-attachments/assets/deb4ecec-6619-494c-8214-4cd8ef900e60">


Implemented hack from https://serverfault.com/questions/857339/backing-up-restoring-postgres-using-pg-dumpall-split-gzip-set-on-error

@Andrew0Hill : New nurs6293_database/Scripts/nurs6293_createdb.sql.gz only in `initdb_fix` branch for testing prior to merging into main.

**Comment by Andrew0Hill** [comment]
Fixed and merged, thanks! Closing this issue.
