### ISSUE TITLE
File write permission

### ISSUE THREAD

**Issue by mgkahn** [Andrew0Hill/NURS6293_environment#2]
<img width="793" alt="image" src="https://github.com/user-attachments/assets/bcc8c5a4-8957-424e-93d9-fd12ae355660">

I think this can be fixed:
In launchDesktop.sh: add USER_ID=`id -u`; GROUP_ID=`id -g` (I do not know the equivalent in WINDOWS)
In dcoker-compose.yml: Replace     
environment:
      - PUID=1000
      - PGID=1000
with
environment:
     - PUID=$(USER_ID)
     - PGUID=$(GROUP_ID)

**Comment by Andrew0Hill** [comment]
I can fix this too, I was going to suggest that we set up everything to write to the /host_shared folder though, just so we minimize the damage if the container is deleted on accident.

**Comment by mgkahn** [comment]
I agree putting everything in /host_shared folder will allow persistence across reloads/updated images. We just need to make sure the local mount is written using the local user's UID/GID rather than 1000/1000.

**Comment by Andrew0Hill** [comment]
Fixed, host_shared works correctly now.
