### ISSUE TITLE
DBeaver: PG driver files need to be preloaded in image

### ISSUE THREAD

**Issue by mgkahn** [Andrew0Hill/NURS6293_environment#3]
<img width="1195" alt="image" src="https://github.com/user-attachments/assets/49a466cc-f6dc-4944-877e-65ca1c0db576">

**Comment by Andrew0Hill** [comment]
Should be very doable, I just need to figure out where DBeaver stores the drivers it downloads, and I can download the same drivers from Maven in the Dockerfile.

**Comment by Andrew0Hill** [comment]
We are not using DBeaver, will re-open if we need this again.
