### ISSUE TITLE
Change GTK3 Background Color Property

### ISSUE THREAD

**Issue by Andrew0Hill** [Andrew0Hill/NURS6293_environment#33]

**Comment by mgkahn** [comment]
Arrrrrgggggggg.
gtk-color-scheme deprecated and now ignored........

<img width="1080" alt="image" src="https://github.com/user-attachments/assets/498fcdaa-e5f8-4e55-856e-ed126a14b8be">

**Comment by Andrew0Hill** [comment]
Still working on this, trying to figure out which property the theme you showed is setting in order to modify the background color.

**Comment by Andrew0Hill** [comment]
Well I have half a solution: 

You can add some custom CSS to `/config/.config/gtk-3.0/gtk.css`, I added 

```
.background {
    color: #242424;
    background-color: whitesmoke;
}
```

which fixes the issue in BIRT but makes everything else (it's a global GTK option) look slightly worse. 

None of the GTK HTML selectors seem to work either, so I can't seem to apply a style just to specific GTK widgets.

**Comment by mgkahn** [comment]
Well, you have gotten further than I have after yet another day of flailing. The "object" that we want to "fix" is Gtk.Button. There are references to CSS_BUTTONFACE_VALUE in the Eclipse source code. I will poke around using your CSS above and see if I can get it to apply itself to just Gtk.Buttons. Probably still global but maybe less disruptive??????  Thanks for working on this. It is so frustrating to have such a small thing ruin the ability to use a tool.

**Comment by mgkahn** [comment]
@Andrew0Hill Can you point me to an example where you thought the above gtk.css change made something slightly worse? I looked at other BIRT screens and also PGModeler and DBeaver (I know, we are not using it). I didn't see anything unsatisfactory with this change.

**Comment by Andrew0Hill** [comment]
It only showed up once I restarted the container (so the XFCE panel will refresh with the new CSS), but the tooltips and panel labels for XFCE were hard to read (light text on light background). I also noticed a few screens in DBeaver that had issues with the text disappearing when selected.
