### ISSUE TITLE
Consider changing desktop background

### ISSUE THREAD

**Issue by mgkahn** [Andrew0Hill/NURS6293_environment#35]
I find the gradient bright colors annoying. Suggesting bland dark grey without gradient.But  I'll go with the group consensus.

To change, right click in any location of desktop and use color picker.
Don't know where in desktop config this information is stored.

<img width="1490" alt="image" src="https://github.com/user-attachments/assets/16beff1d-7dc4-42ff-b4e6-0dd4ba9e57f3">

**Comment by Andrew0Hill** [comment]
We can do this programmatically with some calls to gsettings, like:

```bash
gsettings set org.mate.background color-shading-type solid
gsettings set org.mate.background primary-color 'rgb(36,31,49)'
```

If we decide to change, I can add in the next release.

**Comment by Andrew0Hill** [comment]
Done in v0.1.6
