### ISSUE TITLE
PDF Viewer

### ISSUE THREAD

**Issue by mgkahn** [Andrew0Hill/NURS6293_environment#5]
If we stay with current XFCE desktop, need to include a PDF viewer for viewing PDF Printer output.
MINT desktop may have a PDF Viewer in its installed tools.

**Comment by Andrew0Hill** [comment]
For XFCE, we could also just use the web browser to view PDFs (It's Chromium in XFCE). It doesn't have a ton of features but if they only need it to view the PDFs, it should be sufficient.

**Comment by Andrew0Hill** [comment]
Closing this issue, as we can use Chromium or a PDF viewer on the local machine to view PDFs.
