### ISSUE TITLE
Replace Docker volumes with local file mounts

### ISSUE THREAD

**Issue by mgkahn** [Andrew0Hill/NURS6293_environment#8]
For Postgres and all other local file saves.

PG example: 
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

**Comment by Andrew0Hill** [comment]
Postgres and Webtop images now use local share mounts.
